version: '3.3'
services:
  db:
    image: 'mysql:5.7'
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-data:/docker-entrypoint-initdb.d
    restart: always
    # ports:
      # - ${IP}:3306:3306 # change ip if required
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: "${DB_WORDPRESS_PASSWORD}"
  wordpress:
    depends_on:
      - db
    image: 'wordpress:latest'
    volumes:
      - ./wp-app:/var/www/html # Full wordpress project
      # - ${PWD}/wp-app/wp-content/themes:/var/www/html/wp-content/themes/ # Themes
      # - ${PWD}/plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      # - ${PWD}/theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    ports:
      - ${WP_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: "${DB_WORDPRESS_PASSWORD}"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:${PMA_PORT}:80
    links:
      - 'db:db'
    depends_on:
      - db
  wpcli:
    image: wordpress:cli
    volumes:
      # - ${PWD}/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${PWD}/wp-app:/var/www/html
    depends_on:
      - db
      - wordpress
volumes:
  db_data: {}
